name: SSIS Package Deployment to Azure SQL Managed Instance

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    name: Deploy SSIS to Azure SQL MI
    runs-on: windows-latest

    env:
      SSIS_ISPAC_PATH: 'path/to/your/package.ispac' # Update this path
      AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }} # MI hostname
      AZURE_SQL_DB: 'SSISDB'
      AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
      AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download sqlpackage from Microsoft Download Center
      shell: powershell
      run: |
        $url = "https://download.microsoft.com/download/6/3/6/636A1B6C-2F83-4F80-9A08-687A1D0F2F2C/sqlpackage-win-x64-en-US.zip"
        $zipPath = "$env:RUNNER_TEMP\sqlpackage.zip"
        curl.exe -L $url -o $zipPath
        Expand-Archive -Path $zipPath -DestinationPath "$env:RUNNER_TEMP\sqlpackage"
        Add-Content -Path $env:GITHUB_PATH -Value "$env:RUNNER_TEMP\sqlpackage"
