name: SSIS Package Deployment to Azure SQL Managed Instance

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    name: Deploy SSIS to Azure SQL MI
    runs-on: windows-latest

    env:
      SSIS_ISPAC_PATH: 'path/to/your/package.ispac' # Update this path
      AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }} # MI hostname
      AZURE_SQL_DB: 'SSISDB'
      AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
      AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install sqlpackage using Chocolatey
      shell: powershell
      run: |
        choco install sqlpackage -y
        $sqlPackagePath = "${env:ProgramFiles}\SqlPackage"
        Add-Content -Path $env:GITHUB_PATH -Value $sqlPackagePath
