name: SSIS Package Deployment to Azure SQL Managed Instance

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    name: Deploy SSIS to Azure SQL MI
    runs-on: windows-latest

    env:
      SSIS_ISPAC_PATH: 'path/to/your/package.ispac' # Update this path
      AZURE_SQL_SERVER: ${{ secrets.AZURE_SQL_SERVER }} # MI hostname
      AZURE_SQL_DB: 'SSISDB'
      AZURE_SQL_USER: ${{ secrets.AZURE_SQL_USER }}
      AZURE_SQL_PASSWORD: ${{ secrets.AZURE_SQL_PASSWORD }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download sqlpackage.exe
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://aka.ms/sqlpackage-win" -OutFile "$env:RUNNER_TEMP\sqlpackage.zip"
        if ((Get-Item "$env:RUNNER_TEMP\sqlpackage.zip").Length -gt 0) {
          Expand-Archive -Path "$env:RUNNER_TEMP\sqlpackage.zip" -DestinationPath "$env:RUNNER_TEMP\sqlpackage"
          Add-Content -Path $env:GITHUB_PATH -Value "$env:RUNNER_TEMP\sqlpackage"
        } else {
          Write-Error "sqlpackage.zip download failed or is empty."
          exit 1
        }
